services:
  backend:
    volumes:
      - ./backend:/app
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    ports:
      - 8080:8080

  frontend:
    build:
      context: .
      dockerfile: docker/nodejs/Dockerfile
    ports:
      - "3000:3000" # ホストのポート3000をコンテナのポート80にマッピング
    volumes:
      - ./frontend:/var/www/html/app
    environment:
      - CHOKIDAR_USEPOLLING=true

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf