services:
  back:
    volumes:
      - ./back:/app
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    ports:
      - 8080:8080

  front:
    build:
      context: .
      dockerfile: docker/nodejs/Dockerfile
    volumes:
      - ./front:/src # ローカルをコンテナ内にマウント
    command: sh -c "cd react-project && yarn start" #コンテナを立ち上げたときに自動的にbuildする
    ports:
      - "3000:3000"
 
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf