services:
  backend:
    volumes:
      - ./backend:/app
    tty: true
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    ports:
      - 5001:5000
    #command: flask run --host 0.0.0.0 
    command: python3 server2.py
    
    #environment:
    #  - FLASK_ENV=development
    #  - FLASK_APP=app.py

  redis:
    image: redis

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf